version: '3'
services:
  cratedb-cleanup:
    image: cratedb-cleanup:0.1
    environment:
      - CRATE_HOST=cratedb:4200
      - CRATE_USER=crate
      - CRATE_PASSWORD=
    volumes:
      - ./config.json:/app/config.json
